### ISSUE TITLE
Literally doesn't work

### ISSUE THREAD

**Issue by Zumorica** [Zumorica/Monochrome.GUI#1]
There has been an attempt to port and fix this, but honestly I feel like I'm not knowledegable enough to make it work. Anyone is free to pick this up if they feel like it.

**Comment by ZackUnfair** [comment]
Can confirm, it literally doesn't work.

**Comment by Unbancho** [comment]
On it.

**Comment by Zumorica** [comment]
> On it.

epic gamer moment

**Comment by Zumorica** [comment]
hah, turns out it worked
only needed a spritesheet
